package com.inteliment.counterapi.utils;

public class ServerContent {

	
	public static final String content = "Lorem ipsum dolor sit amet, consecteturadipiscingelit. Nullasedsuscipitmetus, sit amettristiquepurus. Etiam sit ametleosollicitudin, tinciduntlectusvel, ultriciesmauris. Donecultrices lorem in esteleifend, et feugiat libero semper. Duissodales gravida sapienegetefficitur. Utmattismollisblandit. Duisnecmetus gravida, posuere dolor id, pretiumurna. Aliquam vitae purus ex. Etiam vitae ipsum leo. Integer blandit, arcuegetcommodoscelerisque, risusleoaliquetdiam, in sagittismetus ex sedelit. Duisvelurna non estfringillarutrum. Utmolestiesedrisus in pharetra. Maecenas eget ante at nullafeugiateuismod. Suspendisse pharetra porttitor lacus nontristique.\r\n" + 
			"Vivamusvariusposuere ligula. Nullam magna metus, elementumvelelementumeu, elementum non magna. Ut cursus arcuvel ligula mollis, in interdumvelitmaximus. Pellentesquearcu lorem, porttitor et quam vitae, imperdietvenenatis magna. Etiamimperdieteratvellectusrhoncussollicitudin. Praesent at mi a estsuscipittemporsedeu diam. In hachabitasseplateadictumst. Morbierat mi, iaculis id hendrerit a, sollicitudin et ligula. Vivamusjustonibh, cursus at ultriciessed, variusiaculisenim.\r\n" + 
			"Donecconsequatluctussapien, quisaliquam ante tristique sit amet. Pellentesqueaccumsansollicitudin mi a blandit. Donec ac dui bibendum, pharetra nulla vitae, iaculispurus. Donecfermentumporttitormollis. Mauris cursus fringilla ex, egetullamcorper ipsum lacinia in. Nam egetvehicula dui. In egetturpis convallis, ultricesneque vitae, interdumturpis. Nullam non aliquamsapien, egetvolutpatelit. Cras pharetra ex a orcifaucibustristique at ullamcorpernibh. Proinneclacinia ante, eurutrumsem.\r\n" + 
			"Curabitur id libero purus. Vivamusvelvelitturpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Donecat urnaegetaugueefficiturporttitor at euelit. Fuscefeugiattempornulla, at euismod lacus tincidunt sed. Curabiturullamcorperdignissimnisl, egetiaculisorcivestibulum sed. Utconsecteturconsectetururnavestibulumultricies. Maecenas non felisarcu. Fusce in tortormetus. Vestibulumvelfelisut lorem ultriciespretiumquisutmetus. Aliquameratvolutpat. Praesent a lorem porttitor, venenatisnislvolutpat, placerat dui. Vivamusutjustoeuorcitinciduntmalesuada. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiamfacilisisnullavelleopretiumvarius.\r\n" + 
			"Fusceeleifendtinciduntlacinia. Duismaximus, sapien ac fringillapretium, augueleoaliquam ligula, quisrutrumleosemvel magna. Duiscommodolobortis dui, utrhoncus dolor. Class aptenttacitisociosquadlitoratorquent per conubia nostra, per inceptoshimenaeos. Nam necaugueaugue. Quisqueeuorciarcu. Aliquamnequeodio, eleifend a dolor sed, dapibusauctorjusto. Aliquamsollicitudinarcu sit ametodio gravida, necviverranullaefficitur. Phasellussed libero rutrum lacus sollicitudinmattis. Sedfermentumsapien ac dolor elementum, quisvehiculasemtempus.\r\n" + 
			"Etiam et orci non orcilobortis dictum id vitae massa. Aeneaneueratnulla. Sedposuereullamcorper magna, temporultricesjustofeugiatrhoncus. Crasfringilla ligula neceuismodtristique. Duis vitae enimegetaugueconsecteturultricies. Namlaoreetsapienatdictumconsectetur.Suspendissetristiquepurusneque,utblanditnunctinciduntet.\r\n" + 
			"Duispretiumcondimentumdiam id viverra. Pellentesque sit ametdapibuseros, ac auctorlectus. Praesentegettelluspurus. Proinvelnisl sit ametorcilaoreetfaucibusegeteu nisi. Nulla id pharetra arcu. Lorem ipsum dolor sit amet, consecteturadipiscingelit. Vivamusornarelectuseumetusvenenatis, quisporttitornibh convallis. Nullanuncmetus, tristiquequis dui sed, interdumimperdietnisl. Vestibulummattistincidunt lacus, imperdietmattis libero variusrhoncus. Nam in auctornisl. Nunc tinciduntaccumsanpulvinar. Class aptenttacitisociosquadlitoratorquent per conubia nostra, per inceptoshimenaeos. Maurisluctusscelerisqueaugue, velfinibus ligula semper vel. Lorem ipsum dolor sit amet, consecteturadipiscingelit. Class aptenttacitisociosquadlitoratorquent per conubia nostra, per inceptoshimenaeos. Nunc ultriciesvelnuncegetmollis.\r\n" + 
			"Donec ligula felis, ultricesvelblanditut, hendreritvelturpis. Duisfaucibusdapibus mi ac semper. Duis id tortor tempus augueeuismod tempus. Integer vehiculavelitutleoblanditsagittis. Vestibulum ante ipsum primis in faucibusorciluctus et ultricesposuerecubiliaCurae; Pellentesque habitant morbitristiquesenectus et netus et malesuada fames ac turpisegestas. Nunc uturnavelmetusmolestievenenatisnec non dui. Integer diammetus, aliquam a gravida et, varius id nulla. Nunc non porttitor ipsum. Aliquamsapienenim, eleifendnecnunc id, tempus tempus ex. Vivamusnecurnaornare,finibusleo at, posuereurna. Aeneanest mi, porta ac gravida at, hendreritquiselit. Quisqueurnamauris, lobortis sit amettortoreget, laoreetconsecteturtortor. Suspendisse id imperdietnisl, egetpellentesquetortor. Maecenas sit amet mi et ex ornare porta sollicitudin vitae tellus. Donecnulla lorem, imperdiet non sodales vitae, conguequissapien. Quisquenecmattis lacus. Seddapibus nisi nec libero ornare, in accumsan dolor porttitor. Praesentsodalescommodoultricies. Pellentesque habitant morbitristiquesenectus et netus et malesuada fames ac turpisegestas. Cras id ipsum vestibulum, venenatiseros vitae, maximus magna. Mauriseublandittortor, condimentumeleifenddolor.\r\n" + 
			"Craseutellusfeugiat, lobortismetus ac, consecteturorci. Phasellusbibendumtinciduntmassa non venenatis. Nunc sedmolestiemetus, velelementumtortor. Duismalesuada porta nisl ac molestie. In a tellusfaucibus, convallis nuncnec, sodales lacus. Donecvulputateinterdummassasedposuere. In dapibuseu ligula at sodales. Sedfacilisis a semegetlobortis. Utviverra ipsum dictum pharetra auctor. Duistinciduntnullasapien, sit ametfacilisis ante rhoncuseu. Aliquamluctusdolortortor,vitaeinterdumfeliselementumeget.Nammattisleogravidaexelementum,idfacilisislacusornare.\r\n";
			
}
